name: publish_tools
description: A set of tasks the enhance the pub.dev publishing experience.  With a single command push to GitHub, pub.dev and even Homebrew.
version: 1.0.0+9
homepage: https://github.com/faithoflifedev/publish_tools
repository: https://github.com/faithoflifedev/publish_tools

funding:
  - https://www.buymeacoffee.com/faithoflif2

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  crypto: ^3.0.5
  git: ^2.3.0
  github: ^9.24.0
  grinder: ^0.9.5
  http: ^1.2.2
  json_annotation: ^4.9.0
  mustache_template: ^2.0.0
  path: ^1.9.0
  pubspec_parse: ^1.3.0
  recase: ^4.1.0
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  lints: ^5.0.0
  test: ^1.25.8
