name: publish_tools
description: Do you want to commit to GitHub, publish to pub.dev and HomeBrew with one simple command?  Use this package.
version: 0.1.0+12
homepage: https://github.com/faithoflifedev/publish_tools
repository: https://github.com/faithoflifedev/publish_tools

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  crypto: ^3.0.3
  git: ^2.2.1
  github: ^9.19.0
  grinder: ^0.9.4
  http: ^1.1.0
  json_annotation: ^4.8.1
  mustache_template: ^2.0.0
  path: ^1.8.3
  pubspec: ^2.3.0
  recase: ^4.1.0
  universal_io: ^2.2.2
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  lints: ^3.0.0
  test: ^1.24.8
