name: publish_tools
description: Do you want to commit to GitHub, publish to pub.dev and HomeBrew with one simple command?  Use this package.
version: 0.1.0+10
homepage: https://github.com/faithoflifedev/publish_tools
repository: https://github.com/faithoflifedev/publish_tools

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  crypto: ^3.0.2
  git: ^2.2.0
  github: ^9.14.0
  grinder: ^0.9.2
  http: ^1.1.0
  json_annotation: ^4.7.0
  mustache_template: ^2.0.0
  path: ^1.8.2
  pubspec: ^2.3.0
  recase: ^4.1.0
  universal_io: ^2.0.4
  yaml: ^3.1.1

dev_dependencies:
  build_runner: ^2.3.2
  json_serializable: ^6.5.4
  lints: ^2.0.1
  test: ^1.22.0
