name: publish_tools
description: A package for making it easy to publishing Dart/Flutter packages and cli tools.
version: 0.1.0+5
homepage: https://github.com/faithoflifedev/publish_tools
repository: https://github.com/faithoflifedev/publish_tools

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  crypto: ^3.0.2
  github: ^9.4.0
  grinder: ^0.9.2
  http: ^0.13.5
  json_annotation: ^4.6.0
  mustache_template: ^2.0.0
  path: ^1.8.2
  pubspec: ^2.3.0
  recase: ^4.0.0
  universal_io: ^2.0.4
  yaml: ^3.1.1

dev_dependencies:
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  lints: ^2.0.0
  test: ^1.16.0
