/// app metadata
library;

// DO NOT EDIT THIS FILE
// THIS FILE IS AUTOMATICALLY OVER WRITTEN BY PublishTools
import 'dart:convert' show json;

final pubSpec = json.decode(
    '{description: Do you want to commit to GitHub, publish to pub.dev and HomeBrew with one simple command?  Use this package., homepage: https://github.com/faithoflifedev/publish_tools, documentation: null, repository: https://github.com/faithoflifedev/publish_tools, issueTracker: null, name: publish_tools, publish_to: null, version: 1.0.0+6}');
