/// app metadata
library meta;

// DO NOT EDIT THIS FILE
// THIS FILE IS AUTOMATICALLY OVER WRITTEN BY PublishTools
import 'dart:convert' show json;

final pubSpec = json.decode(
    '{"name":"publish_tools","version":"1.0.0-dev.1","homepage":"https://github.com/faithoflifedev/publish_tools","environment":{"sdk":">=3.2.0 <4.0.0"},"description":"Do you want to commit to GitHub, publish to pub.dev and HomeBrew with one simple command?  Use this package.","dependencies":{"crypto":"^3.0.3","git":"^2.2.1","github":"^9.24.0","grinder":"^0.9.5","http":"^1.2.1","json_annotation":"^4.8.1","mustache_template":"^2.0.0","path":"^1.9.0","pubspec":"^2.3.0","recase":"^4.1.0","universal_io":"^2.2.2","yaml":"^3.1.2"},"dev_dependencies":{"build_runner":"^2.4.9","json_serializable":"^6.7.1","lints":"^3.0.0","test":"^1.25.3"},"repository":"https://github.com/faithoflifedev/publish_tools"}');
